/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservashabana;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import javax.swing.*;

/**
 *
 * @author Juan A. García Muelas <juangmuelas@gmail.com>
 * @version 2
 * @since 05/11/21
 */
public class Reservas01 extends javax.swing.JDialog {

    /**
     * Creates new form reservas01
     */
    public Reservas01(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Salón Habana-Reservas"); //añadimos un title para mejorar UX
        //Ponemos como inactivas las elecciones posbles de congresos
        jLNDias.setVisible(true);
        jLNHabitaciones.setVisible(true);
        jSdias.setEnabled(false);
        jShabitaciones.setEnabled(false);
//        jSdias.setVisible(false);
//        jShabitaciones.setVisible(false);
        
        Calendar calendar = Calendar.getInstance();
        
        Date inicio = calendar.getTime();
        //Indicamos año hasta -100 del actual
        calendar.add(Calendar.YEAR, -100);
        //Guardamos la configuración en un DATE
        Date fechaAnterior = calendar.getTime();
        //Indicamos año hasta +200 del actual
        calendar.add(Calendar.YEAR, 200);
        //Guardamos la configuración en un DATE
        Date fechaPosterior = calendar.getTime();
        //Usamos el contructor de abajo para crear un modelo para el Spinner
        //Utilizamos los datos que creamos más arriba
        //Para fecha utilizamos Calendar.YEAR y para hora Calendar.HOUR, el resto puede ser igual
        SpinnerModel fechaModel = new SpinnerDateModel(inicio, fechaAnterior, fechaPosterior, Calendar.YEAR);
//        SpinnerModel horaModel = new SpinnerDateModel(inicio, fechaAnterior, fechaPosterior, Calendar.HOUR);
        //Indicamos el model para cada Spinner además del formato de fecha y hora según corresponda.
        jSfecha.setModel(fechaModel);
        jSfecha.setEditor(new JSpinner.DateEditor(jSfecha, "dd/MM/yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatosContacto = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jTFecha = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jSfecha = new javax.swing.JSpinner();
        jLAsistencia = new javax.swing.JLabel();
        jSAsistentes = new javax.swing.JSpinner();
        jPTipoEvento = new javax.swing.JPanel();
        jCBTipo = new javax.swing.JComboBox<>();
        jLNDias = new javax.swing.JLabel();
        jSdias = new javax.swing.JSpinner();
        jLNHabitaciones = new javax.swing.JLabel();
        jShabitaciones = new javax.swing.JSpinner();
        jPTipoCocina = new javax.swing.JPanel();
        jCBTipoCocina = new javax.swing.JComboBox<>();
        jSeparador = new javax.swing.JSeparator();
        jBConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPDatosContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPDatosContacto.setToolTipText("Datos de Contacto");

        jLNombre.setText("Nombre Completo");

        jTNombre.setToolTipText("Añadir nombre completo");
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jLTelefono.setText("Teléfono");

        jTTelefono.setToolTipText("Añadir teléfono");

        javax.swing.GroupLayout jPDatosContactoLayout = new javax.swing.GroupLayout(jPDatosContacto);
        jPDatosContacto.setLayout(jPDatosContactoLayout);
        jPDatosContactoLayout.setHorizontalGroup(
            jPDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPDatosContactoLayout.setVerticalGroup(
            jPDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosContactoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTelefono)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jTFecha.setToolTipText("Detalles Reserva");

        jLFecha.setText("Fecha Reserva");

        jSfecha.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jSfecha.setModel(new javax.swing.SpinnerDateModel());
        jSfecha.setToolTipText("Elija fecha");

        jLAsistencia.setText("Nº Asistentes Evento");

        jSAsistentes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jSAsistentes.setModel(new javax.swing.SpinnerNumberModel(2, 0, null, 1));
        jSAsistentes.setToolTipText("Indicar número de personas a asistir");

        jPTipoEvento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPTipoEvento.setToolTipText("Tipo de evento");

        jCBTipo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso", " " }));
        jCBTipo.setToolTipText("Elija una opción");
        jCBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoActionPerformed(evt);
            }
        });

        jLNDias.setText("Nº Jornadas");

        jSdias.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jSdias.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        jSdias.setToolTipText("Detalle número de días");
        jSdias.setRequestFocusEnabled(false);

        jLNHabitaciones.setText("Nº Habitaciones");

        jShabitaciones.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jShabitaciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jShabitaciones.setToolTipText("Detalle número de habitaciones");

        javax.swing.GroupLayout jPTipoEventoLayout = new javax.swing.GroupLayout(jPTipoEvento);
        jPTipoEvento.setLayout(jPTipoEventoLayout);
        jPTipoEventoLayout.setHorizontalGroup(
            jPTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPTipoEventoLayout.createSequentialGroup()
                        .addComponent(jLNDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLNHabitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jShabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPTipoEventoLayout.setVerticalGroup(
            jPTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNDias)
                    .addComponent(jSdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNHabitaciones)
                    .addComponent(jShabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPTipoCocina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Cocina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPTipoCocina.setToolTipText("Tipo de Cocina");

        jCBTipoCocina.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBTipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No precisa", "Bufé", "Carta", "Cita con el Chef" }));
        jCBTipoCocina.setToolTipText("Elija una opción");

        javax.swing.GroupLayout jPTipoCocinaLayout = new javax.swing.GroupLayout(jPTipoCocina);
        jPTipoCocina.setLayout(jPTipoCocinaLayout);
        jPTipoCocinaLayout.setHorizontalGroup(
            jPTipoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTipoCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPTipoCocinaLayout.setVerticalGroup(
            jPTipoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTipoCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTFechaLayout = new javax.swing.GroupLayout(jTFecha);
        jTFecha.setLayout(jTFechaLayout);
        jTFechaLayout.setHorizontalGroup(
            jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTFechaLayout.createSequentialGroup()
                        .addComponent(jLFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTFechaLayout.createSequentialGroup()
                        .addComponent(jLAsistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jTFechaLayout.setVerticalGroup(
            jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFecha)
                    .addComponent(jSfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAsistencia)
                    .addComponent(jSAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jTFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBConfirmar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBConfirmar.setText("Confirmar Reserva");
        jBConfirmar.setToolTipText("Confirmar Reserva");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBConfirmar)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparador, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addComponent(jPDatosContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBConfirmar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jCBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoActionPerformed
        // Vamos a mostrar/activar días y habitaciones , solo si está señalada
        // como opción congreso
        
        if(jCBTipo.getSelectedItem()== "Congreso"){
            jSdias.setEnabled(true);
            jShabitaciones.setEnabled(true);
        }else{
            jSdias.setEnabled(false);
            jShabitaciones.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jCBTipoActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        final JFrame jf = new JFrame("Ventana de Confirmacion");
        jf.setSize(1000, 400);
        jf.setLocationRelativeTo(null);
        jf.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        Calendar calendar = Calendar.getInstance();
        
        Date inicio = calendar.getTime();
        //Indicamos año hasta -100 del actual
        calendar.add(Calendar.YEAR, -100);
        //Guardamos la configuración en un DATE
        Date fechaAnterior = calendar.getTime();
        //Indicamos año hasta +200 del actual
        calendar.add(Calendar.YEAR, 200);
        //Guardamos la configuración en un DATE
        Date fechaPosterior = calendar.getTime();
        //Utilizamos los datos que creamos más arriba
        //Para fecha utilizamos Calendar.YEAR y para hora Calendar.HOUR, el resto puede ser igual
        SpinnerModel fechaModel = new SpinnerDateModel(inicio, fechaAnterior, fechaPosterior, Calendar.YEAR);
        //Indicamos el model para cada Spinner además del formato de fecha y hora según corresponda.
        jSfecha.setModel(fechaModel);
        jSfecha.setEditor(new JSpinner.DateEditor(jSfecha, "dd/MM/yyyy"));
        
        String nombre = jTNombre.getText();
        String fecha = new SimpleDateFormat("dd/MM/yyyy").format(jSfecha.getValue());
        String asistencia = jSAsistentes.getValue().toString();
        String evento = jCBTipo.getSelectedItem().toString();
        String cocina = jCBTipoCocina.getSelectedItem().toString();
        
        JOptionPane.showMessageDialog(jf,"<html><b> Confirmada su reserva</b>: "+ nombre +" \n"+
                "<html><b>Fecha: </b>"+ fecha +" \n" +
                "<html><b>Nº Participantes: </b>"+ asistencia +" \n"+
                "<html><b>Evento: </b>"+ evento +" \n"+
                "<html><b>Cocina: </b>"+ cocina +"</html> \n","SALÓN HABANA * Confirmación Reserva",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jBConfirmarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reservas01 dialog = new Reservas01(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JComboBox<String> jCBTipoCocina;
    private javax.swing.JLabel jLAsistencia;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNDias;
    private javax.swing.JLabel jLNHabitaciones;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JPanel jPDatosContacto;
    private javax.swing.JPanel jPTipoCocina;
    private javax.swing.JPanel jPTipoEvento;
    private javax.swing.JSpinner jSAsistentes;
    private javax.swing.JSpinner jSdias;
    private javax.swing.JSeparator jSeparador;
    private javax.swing.JSpinner jSfecha;
    private javax.swing.JSpinner jShabitaciones;
    private javax.swing.JPanel jTFecha;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables
}
