/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservashabana;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan A. García Muelas <juangmuelas@gmail.com>
 * @version 2
 * @since 05/11/21
 */
public class SalonHabana01 extends javax.swing.JFrame {

    /**
     * Creates new form SalonHabana01
     */
    public SalonHabana01() {
        initComponents();
        //Añadimos la imagen de logo para que se muestre como icono
        this.setIconImage(new ImageIcon(getClass().getResource("/reservashabana/img/salon-habana.png")).getImage());
        this.setTitle("Salón Habana"); //añadimos un title para mejorar UX
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBg = new javax.swing.JLabel();
        jBReserva = new javax.swing.JButton();
        jMenuBarReserva = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuReserv = new javax.swing.JMenu();
        jMenuItemReservar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservashabana/img/salon-habana.jpg"))); // NOI18N
        jLBg.setToolTipText("Logo");

        jBReserva.setBackground(new java.awt.Color(102, 0, 0));
        jBReserva.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBReserva.setText("Reservas");
        jBReserva.setToolTipText("Realizar nueva reserva");
        jBReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservaActionPerformed(evt);
            }
        });

        jMenuBarReserva.setToolTipText("Menú principal");
        jMenuBarReserva.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuInicio.setText("Inicio");
        jMenuInicio.setToolTipText("Inicio");
        jMenuInicio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jMenuBarReserva.add(jMenuInicio);

        jMenuReserv.setText("Reservas");
        jMenuReserv.setToolTipText("Reservas");
        jMenuReserv.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItemReservar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemReservar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jMenuItemReservar.setText("Realizar Reserva");
        jMenuItemReservar.setToolTipText("Pulse para Realizar Reserva");
        jMenuItemReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservarActionPerformed(evt);
            }
        });
        jMenuReserv.add(jMenuItemReservar);

        jMenuBarReserva.add(jMenuReserv);

        setJMenuBar(jMenuBarReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLBg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jBReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLBg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBReserva)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservaActionPerformed
        // Creamos la conexión con el JDialog para las reservas
        Reservas01 reservas01 = new Reservas01(this, true);
        //ponemos la visibilidad a true para que sea modal
        reservas01.setVisible(true);
    }//GEN-LAST:event_jBReservaActionPerformed

    private void jMenuItemReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservarActionPerformed
        // TODO add your handling code here:
        new Reservas01(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalonHabana01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalonHabana01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalonHabana01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalonHabana01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalonHabana01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReserva;
    private javax.swing.JLabel jLBg;
    private javax.swing.JMenuBar jMenuBarReserva;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemReservar;
    private javax.swing.JMenu jMenuReserv;
    // End of variables declaration//GEN-END:variables
}
